version: '3.8'

services:
  app:
    image: php:8.2-fpm  # Actualizado a PHP 8.2
    container_name: laravel_reto_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - appnet
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel_reto_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge